<?php

include_once "main.php";
$object = Singleton::getInstance();
//create a data base called career
$object->createDbt("career");

//start the database
$conn = $object->startDB("career");

$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
$object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");

?>