<?php

include_once "main.php";
$object = Singleton::getInstance();
//create a data base called career
//$object->createDbt("career");

//start the database
$conn = $object->startDB("userregistration");

function all($conn ,$object){
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "appmath", "Applied Mathematics", "<p>The applied mathematics major offers another option for students with quantitative skills and with an interest in a field outside of mathematics. Courses from the three disciplines of mathematics, statistics, and computer and information science are integrated to form a coherent undergraduate program. The major also includes a related field, such as economics, industrial and systems engineering, geological sciences, or insurance, in which quantitative methods are applied. <strong>[MATHEMATICAL SCIENCES]</strong></p>");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");
    $object->insertIntoTableCareer($conn, "tag", "Biotechnology", "Biotechnology Biotechnology may be broadly defined as the application of principles of molecular and cell science in the production of biologically -important or industrially-useful products. Students in the Biotechnology major, therefore, will acquire a strong foundation in the life and chemical sciences; learn how fundamental science is applied to problems through biotechnology; develop basic laboratory skills, perform standard techniques, work with state-of-the-art instrumentation, describe and evaluate analytical methodology used in biotechnology; and become familiar with societal concerns and governmental regulations regarding the biotechnology industry. [SCIENCE]");

}

?>